# -*- coding: utf-8 -*-
from . import tour_deduction_policy
from . import tour_destination
from . import tour_facility
from . import tour_package_type
from . import tour_policy
from . import tour_season
from . import hotel_type
from . import room_type
from . import service_type
from . import hotel_information
from . import transport_carrier
from . import travel_class
from . import transport_information
from . import transport_booking
from . import insurance_type
from . import insurance_policay
from . import hotel_reservation
from . import tour_booking
from . import tour_program
from . import sale_order_inherit
from . import agent_commission
from . import tour_preference
from . import tour_itinary
from . import tour_package
from . import tour_cancellation
