# -*- coding: utf-8 -*-
{
    'name': 'Employee Loan Management',
    'summary': "Streamline employee loan management with our powerful application, simplifying financial transactions and enhancing workplace efficiency.",
    'description': """
        The Odoo Employee Loan Management Module is a comprehensive solution designed to streamline and automate the loan application, approval, and repayment processes for employees within your organization. This module offers a user-friendly interface and customizable features to simplify loan management while ensuring compliance and transparency.
        """,
    'author': "Dynexcel",
    'website': "https://www.dynexcel.com",
    'category': 'Human Resources',
    'version': '0.4',
    'live_test_url': 'https://youtu.be/BwokAjL_KZU',
    'depends': ['base', 'hr', 'account','hr_contract','de_hr_workspace'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/loan_data.xml',
        'data/mail_data.xml',
        'views/hr_loan.xml',
        'wizard/loan_reject_wizard_views.xml',
        'wizard/loan_reschedule_wizard_views.xml',
        'wizard/save_xlsx_views.xml',
        'wizard/report_loan_xlsx_wizard_views.xml',
        'wizard/loan_scheduler_compute_views.xml',
        'views/res_config_settings.xml',
        'views/hr_loan_reschedule_views.xml',
        'views/hr_loan_schedule_views.xml',
        'views/hr_loan_dashboard_views.xml',
        'views/hr_loan_type_views.xml',
        'views/hr_loan_views.xml',
        'reports/report_loan_views.xml',
        'reports/report_loan.xml',
        'views/my_loan_workspace_views.xml',
        
    ],
    'license': 'OPL-1',
    'price': 75,
    'currency': 'USD',
    'images': ['static/description/banner.jpg'],
    'installable': True,
    'application': False,
    'auto_install': False,
}
